In [1]:
import numpy as np
import pandas as pd

In [3]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.random.random((2,3))

array([[0.4909055 , 0.00616524, 0.4630665 ],
       [0.10068009, 0.60257096, 0.64942549]])

In [7]:
np.ones((3,2), )

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.full?

In [11]:
arr = [1,2,3,4,5,6]
a = np.array(arr)
np.full((2,6), a)

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [12]:
e = np.array(([10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]))
e

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [13]:
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [16]:
e[[2,0,3,1], [2,1,0,2]]

array([18, 11, 19, 15])

In [17]:
e[e>15]

array([16, 17, 18, 19, 20, 21])

In [2]:
days = np.array(['Monday', 'Tuesday', 'Wednesday', 'Thursday'])
np_days = pd.Series(days)
np_days

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
dtype: object

In [11]:
dys = pd.Series(['Monday', 'Tuesday', 'Wednesday', 'Thursday'], index = ['a', 'b', 'c', 'd']) 

In [12]:
dys

a       Monday
b      Tuesday
c    Wednesday
d     Thursday
dtype: object

In [10]:
days2 = pd.Series({'a':'Monday', 'b':'Tuesday', 'c':'Wednesday', 'd':'Thursday'})
days2

a       Monday
b      Tuesday
c    Wednesday
d     Thursday
dtype: object

In [14]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [16]:
df_list = [['Ghana', 'Accra', 10000, 60], 
          ['Nigeria', 'Abuja', 12000, 76], 
          ['Kenya', 'Nairobi', 19876, 29], 
          ['Togo', 'Lome', 987000, 86]]
df = pd.DataFrame(df_list, columns=['Country', 'Capital', 'Population', 'Age'], index=[1,2,3,4])
df

Country  Capital  Population  Age
1    Ghana    Accra       10000   60
2  Nigeria    Abuja       12000   76
3    Kenya  Nairobi       19876   29
4     Togo     Lome      987000   86

In [18]:
df.iloc[3,2]

987000

In [20]:
df.iloc[1]

Country       Nigeria
Capital         Abuja
Population      12000
Age                76
Name: 2, dtype: object

In [22]:
df.iloc[1:, 1:]

Capital  Population  Age
2    Abuja       12000   76
3  Nairobi       19876   29
4     Lome      987000   86

In [23]:
df.loc[2,'Capital']

'Abuja'

In [24]:
df.Age

1    60
2    76
3    29
4    86
Name: Age, dtype: int64

In [26]:
df.at[1,'Capital']

'Accra'

In [27]:
df.iat[1,0]

'Nigeria'

In [28]:
df['Population'].sum()

1028876

In [29]:
df.mean()

C:\Users\owner\AppData\Local\Temp\ipykernel_10472\3698961737.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


Population    257219.00
Age               62.75
dtype: float64

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 1 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Country     4 non-null      object
 1   Capital     4 non-null      object
 2   Population  4 non-null      int64 
 3   Age         4 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 332.0+ bytes


In [33]:
df.describe(include='all')

Country Capital     Population      Age
count        4       4       4.000000   4.0000
unique       4       4            NaN      NaN
top      Ghana   Accra            NaN      NaN
freq         1       1            NaN      NaN
mean       NaN     NaN  257219.000000  62.7500
std        NaN     NaN  486539.343915  24.9182
min        NaN     NaN   10000.000000  29.0000
25%        NaN     NaN   11500.000000  52.2500
50%        NaN     NaN   15938.000000  68.0000
75%        NaN     NaN  261657.000000  78.5000
max        NaN     NaN  987000.000000  86.0000

In [34]:
df.describe()

Population      Age
count       4.000000   4.0000
mean   257219.000000  62.7500
std    486539.343915  24.9182
min     10000.000000  29.0000
25%     11500.000000  52.2500
50%     15938.000000  68.0000
75%    261657.000000  78.5000
max    987000.000000  86.0000

In [32]:
df.corr()

Population       Age
Population    1.000000  0.616106
Age           0.616106  1.000000